--// initial_club_data
-- Migration SQL that makes the change goes here.

TRUNCATE TABLE `team`;
TRUNCATE TABLE `league`;

INSERT INTO `league` (`id`, `name`, `desc`, `creatorId`, `logoUrl`)
VALUES
  (1, 'England Primere League', '', (select `id` from `user` where type=2 order by `id` limit 0,1), ''),
  (2, 'Spanish Primere Liga', '', (select `id` from `user` where type=2 order by `id` limit 0,1), ''),
  (3, 'Italian Serie A', '', (select `id` from `user` where type=2 order by `id` limit 0,1), ''),
  (4, 'French Ligue 1', '', (select `id` from `user` where type=2 order by `id` limit 0,1), ''),
  (5, 'German Bundesliga', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '');

INSERT INTO `team` (`id`, `name`, `desc`, `type`, `leagueId`, `city`, `country`, `creatorId`, `stadium`, `logoUrl`)
VALUES
  (1, 'Arsenal ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(2, 'Aston Villa ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(3, 'Burnley  ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(4, 'Chelsea ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(5, 'Crystal Palace ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(6, 'Everton ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(7, 'Hull ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(8, 'Leicester ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(9, 'Liverpool ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(10, 'Manchester City ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(11, 'Manchester United ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(12, 'Newcastle ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(13, 'QPR ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(14, 'Southampton ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(15, 'Stoke ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(16, 'Sunderland ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(17, 'Swansea City', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(18, 'Tottenham ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(19, 'West Bromwich ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(20, 'West Ham ', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(21, 'Leeds United', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(22, 'Fulham', '', 0, 1, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(23, 'Atletico Madrid ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(24, 'Barcelona ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(25, 'Real Madrid  ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(26, 'Athletic Bilbao ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(27, 'Sevilla ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(28, 'Villarreal ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(29, 'Real Sociedad  ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(30, 'Valencia ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(31, 'Celta ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(32, 'Levante  ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(33, 'Malaga  ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(34, 'Rayo Vallecano  ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(35, 'Getafe ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(36, 'Espanyol ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(37, 'Ciudad de Murcia ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(38, 'Elche ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(39, 'Almeria ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(40, 'Osasuna ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(41, 'Valladolid ', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(42, 'Betis', '', 0, 2, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(43, 'Juventus', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(44, 'AS Roma ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(45, 'Napoli', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(46, 'Fiorentina ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(47, 'Inter', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(48, 'Parma ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(49, 'Torino  ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(50, 'Milan ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(51, 'Lazio ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(52, 'Verona  ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(53, 'Atalanta  ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(54, 'Sampdoria ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(55, 'Genoa ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(56, 'Udinese ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(57, 'Cagliari ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(58, 'Chievo ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(59, 'Sassuolo ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(60, 'Catania ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(61, 'Bologna ', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(62, 'Livorno', '', 0, 3, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(63, 'Monaco FC ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(64, 'Saint-Etienne ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(65, 'EA Guingamp ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(66, 'Evian TG FC ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(67, 'Lorient ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(68, 'Metz ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(69, 'Nantes ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(70, 'Girondins de Bordeaux ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(71, 'LOSC Lille ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(72, 'Montpellier H¨¦rault SC ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(73, 'Nice ', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(74, 'Olympique de Marseille', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(75, 'Olympique Lyonnais', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(76, 'Paris Saint-Germain', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(77, 'Lens', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(78, 'Bastia', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(79, 'Caen', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(80, 'Stade de Reims', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(81, 'Stade Rennais FC', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(82, 'Toulouse FC', '', 0, 4, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(83, 'Bayren Munich', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(84, 'Borussia Dortmund Borussia Dortmund', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(85, 'Eintracht  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(86, 'Augsburg ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(87, 'K_ln  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(88, 'Freiburg', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(89, 'Hamburger  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(90, 'Hannover 96', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
(91, 'Hertha BSC  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (92, 'Leverkusen ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (93, 'Mainz ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (94, 'M_nchengladbach ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (95, 'Paderborn 07 ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (96, 'Schalke 04  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (97, 'Stuttgart  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (98, 'TSG Hoffenheim  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (99, 'Werder Bremen  ', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', ''),
  (100, 'Wolfsburg', '', 0, 5, '', '', (select `id` from `user` where type=2 order by `id` limit 0,1), '', '');


--//@UNDO
-- SQL to undo the change goes here.
TRUNCATE TABLE `team`;
TRUNCATE TABLE `league`;

